### ISSUE TITLE
Incompatible with redmine_checklists

### ISSUE THREAD

**Issue by MayamaTakeshi** [MayamaTakeshi/redmine_rt#33]
When I have this plugin installed
and click 'Submit' on the Edit window, this happens:
```
NoMethodError in IssuesController#update
undefined method `checklists' for nil:NilClass
Extracted source (around line #53):


51
52        def save_before_state
53          @issue.old_checklists = @issue.checklists.to_json
54          checklists_params = params[:issue].present? && params[:issue][:checklists_attributes].present? ? params[:issue][:checklists_attributes] : {}
55          @issue.removed_checklist_ids =
56            if checklists_params.present?
```

We can see this plugin have this patch:

```
$ find . -type f|xargs grep save_before_state
./redmine_checklists/lib/redmine_checklists/patches/issues_controller_patch.rb:          before_action :save_before_state, :only => [:update]
./redmine_checklists/lib/redmine_checklists/patches/issues_controller_patch.rb:        def save_before_state
$ 
```
It does some patching in issues_controller that seem to be incompatible with redmine_rt.

**Comment by MayamaTakeshi** [comment]
It seems there are issues when more than one plugin patches the same controller (in this case, IssuesController).
In particular, calling the before_action methods.
I removed those from my patch and it seems OK now.

**Comment by AndreySolod** [comment]
Ok, I am testing solution, details the sequence of actions in #32, launched via the command:
`bundle exec rails server -e production -b 0.0.0.0`
And got the following problem: notes are created, attached, but not dynamically. Log in console:
![image](https://user-images.githubusercontent.com/32464577/235389595-654b5a9c-f44b-4084-aac1-4476b6dfda36.png)
In production.log all ok.
REST-service is enabled, JSON support too.
Also, Redmine thinks that someone else has updated the task:
![image](https://user-images.githubusercontent.com/32464577/235390189-2d3696d0-7753-4116-bb12-6ecd5b2ff56c.png)
Ok, let's open new tab and try again...
oh, looks like there are an error in console:
![image](https://user-images.githubusercontent.com/32464577/235390219-b7702b4f-567e-46e4-9c9b-c82031d2dfbb.png)
The error is reproduced every time - from the tasks page we go -> Projects -> our project -> issues -> 1. Leaves after page reload. Browser - yandex (chrome like).
Mozilla Firefox is still sadder, and the error, apparently, is not related to some kind of cache, as I initially thought - it is reproduced both on Firefox and in private mode on yandex. Probably, you need to wait a day again until everything is magically repaired:(
