### ISSUE TITLE
Support Installing

### ISSUE THREAD

**Issue by SinghNanak** [MayamaTakeshi/redmine_rt#37]
I amusing Bitnami Redmine 5.0x in windows. Kindly assist me with installation process. I had some confutation about redis-server.

**Comment by MayamaTakeshi** [comment]
Hi, I don't use Windows.
Maybe you could at first try to use VirtualBox to run a linux VM to have a working installation, then try to adjust and discover what is necessary to run on Windows.

**Comment by MayamaTakeshi** [comment]
Alternatively, you can use docker and run redis on it.
