### ISSUE TITLE
Added note ID is always 1.

### ISSUE THREAD

**Issue by sk-ys** [MayamaTakeshi/redmine_rt#47]
### Screenshot
![image](https://github.com/MayamaTakeshi/redmine_rt/assets/963792/5fa288d5-1bcd-400f-83b3-dc3b16756ce4)

My environment as follows:
```
Environment:
  Redmine version                5.1.0.devel
  Ruby version                   3.1.4-p223 (2023-03-30) [x64-mingw-ucrt]
  Rails version                  6.1.7.6
  Environment                    development
  Database adapter               PostgreSQL
```

My guess is that the same error occurs in Redmine 4.1 and later. 
In this line, `$history_children` has `div.tabs` and `div#tab-content-history`.
```JavaScript
var $history_children = $history.find("> div");
```
https://github.com/MayamaTakeshi/redmine_rt/blob/master/assets/javascripts/channels/issue_channel.js#L182
However, you probably wanted to get `div.journal` instead.

#### Page Source
<img width="390" alt="image" src="https://github.com/MayamaTakeshi/redmine_rt/assets/963792/640a538f-e79f-4cee-96cd-9b07bc4e17f4">

#### Browser console
<img width="459" alt="image" src="https://github.com/MayamaTakeshi/redmine_rt/assets/963792/8460912d-9885-4663-b238-9912b26dc45b">

**Comment by MayamaTakeshi** [comment]
Indeed. I didn't notice it because the issue happened only in case of
  "Display comments" = "In chronological order"   
which I was not using. Thanks.
