### ISSUE TITLE
Distance of time formatting in the notes header is different from the original

### ISSUE THREAD

**Issue by sk-ys** [MayamaTakeshi/redmine_rt#49]
The distance of time formatting in the notes header is different from the original.
![image](https://github.com/MayamaTakeshi/redmine_rt/assets/963792/a3792218-e46d-493c-8ff1-57e9f4c17aed)

Distance of time is generated in `ApplicationHelper::time_tag`, but it seems that the `@project` variable is undefined,resulting in the generation of HTML with an `<abbr>` tag.

Tthe `ApplicationHelper::time_tag` is defined as follows:
https://github.com/redmine/redmine/blob/e4a39a28ee67ae8a32100be2f2e4919e15e97396/app/helpers/application_helper.rb#L696-L707

**Comment by MayamaTakeshi** [comment]
Thank you.
