### ISSUE TITLE
jsToolbar is not showing after updating issue with action cable

### ISSUE THREAD

**Issue by sk-ys** [MayamaTakeshi/redmine_rt#51]
jsToolbar is not showing after updating issue with action cable.
<img width="300" alt="image" src="https://github.com/MayamaTakeshi/redmine_rt/assets/963792/3b7b51f6-4737-4bb0-8a08-e2a3dae4b75e">

jsToolbar is initialized in JavaScript in the original Redmine as follows.
```HTML
<script>
//<![CDATA[
var wikiToolbar = new jsToolBar(document.getElementById('issue_description')); wikiToolbar.setHelpLink('/help/en/wiki_syntax_common_mark.html'); wikiToolbar.setPreviewUrl('/preview/text'); wikiToolbar.draw();
//]]>
</script>
```

However, the innerHTML property cannot call scripts.
Relevant part: https://github.com/MayamaTakeshi/redmine_rt/blob/ccdcd0bda736b1172e0f9802b5f290c118ba31cd/assets/javascripts/channels/issue_channel.js#L256-L258

**Comment by MayamaTakeshi** [comment]
Thank you.
