### ISSUE TITLE
Please publish gem render_parent on rubygems.org

### ISSUE THREAD

**Issue by leoniscsem** [MayamaTakeshi/redmine_rt#6]
Installing the plugin **redmine_rt** the regular way from inside mainland China is impossible due to the fetching steps of getting the newest version of **render_parent** due to the Great Firewall of China. I had to manually clone the gem repo on an outside server, scp it manually to the Chinese server and state the path / local bundle config in the Gemfile of the plugin.

As far as I know [Rubygems](https://rubygems.org) mirrors gems on [Ruby-China](https://gems.ruby-china.com), which helps with all Ruby-based web applications. Using proxy configurations for git cloning, while executing any `bundle` tasks as `redmine` system user is overly complex and often times out or creates issues with the SSL handshakes.

I would be much easier to use this plugin, if the gem was published at an accessible repository.

**Comment by MayamaTakeshi** [comment]
Sorry, I was using my own fork of render_parent as my PR to the original project was in limbo. 
However, my PR was accepted 2 years later:
  https://github.com/anteo/render-parent/pull/2
but I didn't update the redmine_rt Gemfile.

The updated version of render_parent is available as:
  https://gems.ruby-china.com/gems/render_parent
I tested with it and it worked.

So I updated the Gemfile now:
  https://github.com/MayamaTakeshi/redmine_rt/commit/44a68b0b288973562d2d08b746fa39693a83bac3

Thanks for reporting.

**Comment by leoniscsem** [comment]
I upgraded the plugin, but obviously Ruby-China has not mirrored the gem yet. I am going to find out how to invoke an auto-publish for the gem, so that they pull it directly after each release. Links are in Chinese only, so we might need to work together, so that I can handle that for you. 

https://ruby-china.org/

**Comment by MayamaTakeshi** [comment]
The plugin version 0.1.0 is there:
  https://gems.ruby-china.com/gems/render_parent/versions/0.1.0
I updated redmine_rt/Gemfile with the required version ID to avoid confusion.

**Comment by leoniscsem** [comment]
My bad, I could not find the gem, and when I upgraded the plugin the `bundle exec rake` process showed an error being unable to download the gem from ruby-china.com. I need to look deeper into this.
